account/urls.py
from django.conf.urls import url
from account.views import *

urlpatterns = [
    url(r'^register', RegisterView.as_view(), name='register'),
    url(r'^login', LogInView.as_view(), name='login'),
    url(r'^logout', LogOutView.as_view(), name='logout'),
]

crossin_weibo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from pro_weibo.views import index
from .views import Index

urlpatterns = [
    url(r'^weibo/', include('weibo.urls', namespace='wb')),
    url(r'^accounts/', include('account.urls', namespace='account')),
    url(r'^admin/', admin.site.urls),
    # url(r'^$', index, name='index'),
    url(r'^$', Index.as_view(), name='index'),
]

weibo/urls.py
from django.conf.urls import url
from weibo import views

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    # url(r'^$', views.HomePageView.as_view(), name='homepage'),
    url(r'^update', views.wb_update, name='update'),
    # url(r'^update', views.WBUpdate.as_view(), name='update'),
    # url(r'^u', views.UserPageView.as_view(), name='upage'),
    url(r'^comment', views.wb_comment, name='comment'),
    url(r'^forward', views.wb_forward, name='forward'),
    url(r'^follow', views.user_follow, name='follow'),
    url(r'^unfollow', views.user_unfollow, name='unfollow'),
    url(r'^u', views.user_page, name='upage'),
]

weibo/models.py
from django.db import models
from django.contrib.auth.models import User
import json
# Create your models here.


class WBUser(User):
    """
    继承 django 默认 User 类，扩充字段及方法
    """
    GENDER_OPTIONS = (
        (0, '保密'),
        (1, '男'),
        (2, '女'),
        (3, '其他')
    )
    nickname = models.CharField(verbose_name='昵称', max_length=60, null=True, blank=True)
    gender = models.IntegerField(verbose_name='性别', choices=GENDER_OPTIONS, default=0)
    _info = models.TextField(verbose_name='其他信息', blank=True, null=True)
    # ManyToManyField 的首个参数指定被关联的类，
    # 此处 WBUser 尚未定义完成，可用字符串形式“临时”代替，正式添加 followers 时，django 会自动替换为 WBUser 对象
    followers = models.ManyToManyField('WBUser', verbose_name='粉丝')

    @property
    def name(self):
        """
        返回用户名字，优先显示昵称
        装饰器 @property 可以使被装饰的函数以属性的形式调用，如 self.name
        """
        return self.nickname or self.username

    @property
    def info(self):
        """
        读取字段 _info，将 json 格式字符串转换为字典
        """
        return json.loads(self._info)

    def save_user_info(self, info: dict):
        """
        保存字段 _info，将字典转换为 json 格式的字符串
        info: dict —— `: dict` 用来指定参数 info 是类 dict 的对象，用来指定参数的格式
        """
        self._info = json.dumps(info)
        self.save()

    def follow(self, user: 'WBUser'):
        """
        关注
        user: 'WBUser' —— `: 'WBUser'` 用来指定参数 user 是类 WBUser 的对象，用来指定参数的格式
        此处 WBUser 尚未定义完成，可用字符串形式“临时”代替，正式添加传递参数时，django 会自动替换为 WBUser 对象
        """
        self.followers.add(user)

    def unfollow(self, user: 'WBUser'):
        """
        解除关注
        """
        self.followers.remove(user)

    def update(self, msg: str):
        """
        发布微博
        """
        wbt = WBText.objects.create(author=self, msg=msg)
        wb = WeiBo.objects.create(user=self, text=wbt)
        return wb

    def forward(self, wb: 'WeiBo'):
        """
        转发微博
        """
        return WeiBo.objects.create(user=self, text=wb.text)

    def __str__(self):
        return self.name


class WBText(models.Model):
    """
    文字微博
    """
    author = models.ForeignKey(WBUser, verbose_name='作者', related_name='ori_wbs')
    msg = models.TextField(verbose_name='微博', max_length=500)

    def __str__(self):
        return '{msg}...'.format(msg=self.msg[:20])


class WeiBo(models.Model):
    """
    微博信息
    """
    user = models.ForeignKey(WBUser, verbose_name='用户', related_name='wbs')
    time_create = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    is_del = models.BooleanField(verbose_name='是否删除', default=False)
    text = models.ForeignKey(WBText, verbose_name='文本', related_name='wbs')

    def del_this(self):
        """
        删除微博
        """
        self.is_del = True
        self.save()

    def comment_this(self, user: WBUser, text: str):
        """
        评论微博
        """
        comment = Comment.objects.create(target=self, user=user, text=text)
        return comment

    def __str__(self):
        return self.text.__str__()


class Comment(models.Model):
    """
    评论
    """
    target = models.ForeignKey(WeiBo, verbose_name='微博', related_name='comments')
    user = models.ForeignKey(WBUser, verbose_name='用户', related_name='comments')
    text = models.TextField(verbose_name='评论', max_length=500)
    time_create = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    is_del = models.BooleanField(verbose_name='是否删除', default=False)

    def del_this(self):
        """
        删除评论
        """
        self.is_del = True
        self.save()

    def __str__(self):
        return '{msg}...'.format(msg=self.text[:20])

weibo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
# from django.views import View
from django.contrib.auth.decorators import login_required
# from django.utils.decorators import method_decorator
from weibo.models import *
# Create your views here.


# @method_decorator(login_required, 'dispatch')
# class HomePageView(View):
#    """
#   class base views
#   """
#     def get(self, request):
#         wb_user = get_object_or_404(WBUser, id=request.user.id)
#         # wbs = WeiBo.objects.all().order_by('-time_create')
#         return render(request, 'weibo/homepage.html', {
#             'wb_user': wb_user,
#             # 'wbs': wbs
#         })


@login_required
def homepage(request):
    """
    个人中心
    """
    user = get_object_or_404(WBUser, id=request.user.id)
    wbs = WeiBo.objects.filter(user__in=user.followers.all()).order_by('-time_create')[:10]
    return render(request, 'weibo/homepage.html', {
        'user': user,
        'wbs': wbs
    })


# class UserPageView(View):
#     def get(self, request):
#         uid = request.GET.get('uid')
#         wb_user = get_object_or_404(WBUser, id=uid)
#         wbs = WeiBo.objects.filter(user=wb_user).order_by('-time_create')
#         return render(request, 'weibo/user_page.html', {
#             'wb_user': wb_user,
#             'wbs': wbs
#         })


def user_page(request):
    """
    用户主页
    """
    uid = request.GET.get('uid')
    wb_user = get_object_or_404(WBUser, id=uid)
    user = get_object_or_404(WBUser, id=request.user.id)
    wbs = WeiBo.objects.filter(user=wb_user).order_by('-time_create')
    return render(request, 'weibo/user_page.html', {
        'wb_user': wb_user,
        'wbs': wbs,
        'user': user
    })


# class WBUpdate(View):
#     def post(self, request):
#         wb_user = get_object_or_404(WBUser, id=request.user.id)
#         msg = request.POST.get('msg')
#         wb = wb_user.update(msg)
#         return HttpResponse(render(request, 'weibo/new_wb.html', {'wb': wb}))


def wb_update(request):
    """
    发送微博
    """
    wb_user = get_object_or_404(WBUser, id=request.user.id)
    msg = request.POST.get('msg')
    wb = wb_user.update(msg)
    return HttpResponse(render(request, 'weibo/new_wb.html', {'wb': wb}))


def wb_comment(request):
    """
    微博评论
    """
    wb_user = get_object_or_404(WBUser, id=request.user.id)
    msg = request.POST.get('msg')
    wid = request.POST.get('wid')
    wb = get_object_or_404(WeiBo, id=wid)
    comment = wb.comment_this(user=wb_user, text=msg)
    return HttpResponse(render(request, 'weibo/new_comm.html', {'comm': comment}))


def wb_forward(request):
    """
    微博转发
    """
    wb_user = get_object_or_404(WBUser, id=request.user.id)
    msg = request.POST.get('msg')
    wid = request.POST.get('wid')
    wb = get_object_or_404(WeiBo, id=wid)
    new_wb = wb_user.forward(wb)
    if msg:
        new_wb.comment_this(user=wb_user, text=msg)
    # redirect 接受 url name 参数，返回一个可以被 views return 返回的对象 HttpResponseRedirect
    response = redirect('wb:upage')
    # HttpResponseRedirect['Location'] 为跳转地址，下面的代码为地址直接拼接 get 参数
    response['Location'] += '?uid={uid}'.format(uid=wb_user.id)
    # HttpResponseRedirect 对象可以直接 return 返回，页面跳转到 response['Location'] 所指定的地址
    return response


def user_follow(request):
    """
    关注用户
    """
    uid = request.GET.get('uid')
    wb_user = get_object_or_404(WBUser, id=uid)
    user = get_object_or_404(WBUser, id=request.user.id)
    user.follow(wb_user)
    return HttpResponse()


def user_unfollow(request):
    """
    解除关注
    """
    uid = request.GET.get('uid')
    wb_user = get_object_or_404(WBUser, id=uid)
    user = get_object_or_404(WBUser, id=request.user.id)
    user.unfollow(wb_user)
    return HttpResponse()

weibo/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
	{% load static %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel='stylesheet' type='text/css' href="{% static 'bootstrap3\css\bootstrap.min.css' %}" />
	<link rel='stylesheet' type='text/css' href="{% static 'bootstrap3\css\bootstrap-theme.min.css' %}" />
	<link rel='stylesheet' type='text/css' href="{% static 'bootstrap3\css\bootstrap-datetimepicker.min.css' %}" />
	{% block link %}{% endblock %}
    <title>{% block title %}标题{% endblock %}</title>
</head>
<body class='container-fluid'>

<header class='row'>
	{% block base_header %}页眉{% endblock %}
</header>

{% block base_header_to_content %}{% endblock %}

<content class='row'>
{% block base_content %}{% endblock %}
</content>

{% block base_content_to_footer %}{% endblock %}

<footer class='row'>
	{% block base_footer %}
		<p class='text-center'><b><a>***感谢访问***</a></b></p>
	{% endblock %}
</footer>

{% block base_more %}{% endblock %}
<script src="{% static 'bootstrap3\js\jquery.min.js' %}" charset="UTF-8"></script>
<script src="{% static 'bootstrap3\js\bootstrap.min.js' %}"></script>
<script src="{% static 'bootstrap3\js\npm.js' %}"></script>
<script src="{% static 'bootstrap3\js\moment.min.js' %}"></script>
<script src="{% static 'bootstrap3\js\bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script src="{% static 'bootstrap3\js\bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
{% block base_script %}{% endblock %}
</body>
</html>

weibo/templates/base_page.html
{% extends 'base.html' %}
{% block base_header %}
<p class='pull-right'>
	<span><a href='{% url "index" %}'>首页</a></span>
	<span>|</span>
	<span><a href='{% url "account:logout" %}'>退出登录</a></span>
</p>
	{% block header %}
	<h4 class='text-center'>crossin的编程教室·简易微博</h4>
	{% endblock %}
{% endblock %}

{% block base_header_to_content %}<hr />{% endblock %}

{% block base_content %}
<div class='col-md-2'>
	{% block left %}
	<div class="list-group">
		<a href="{% url 'index' %}" class="list-group-item text-center">首页</a>
		<a href="{% url 'wb:homepage' %}" class="list-group-item text-center">个人中心</a>
		<a href="{% url 'wb:upage' %}?uid={{ user.id }}" class="list-group-item text-center">我的主页</a>
	</div>
	{% block left_more %}{% endblock %}
	{% endblock %}
</div>
<div class='col-md-10'>
	{% block right %}
	<input class='form-control'>
	{% endblock %}
</div>
{% endblock %}

{% block base_content_to_footer %}<hr />{% endblock %}
{% block base_more %}
	{% block modal %}{% endblock %}
{% endblock %}
{% block base_script %}
	{% block script %}{% endblock %}
{% endblock %}

weibo/templates/index.html
{% extends 'base.html' %}
{% block title %}首页{% endblock %}
{% block base_header %}
	<h1 class='text-center'>简易微博</h1>
{% endblock %}
{% block base_header_to_content %}<hr />{% endblock %}
{% block base_content %}
{% if user.is_authenticated %}
<div class="jumbotron container-fluid">
	<div class='row'>
		<div class='col-md-4'>
			<h1><a href='{% url "wb:homepage" %}'>个人中心</a></h1>
			<h1><a href='{% url "wb:upage" %}?uid={{ user.id }}'>我的主页</a></h1>
		</div>
		<div class='col-md-8'>
			<h1>crossin 的编程教室<small>大作业——</small></h1>
			<h1 class='text-center'><i class='text-danger'>简易微博</i></h1>
		</div>
	</div>
	<div class='row'>
		<p><a class='btn btn-primary pull-right' href='{% url "account:logout" %}'>退出登录</a></p>
	</div>
</div>
<hr />
<table class="table table-hover table-striped table-bordered">
	<caption>
		<h3 class='text-center'>新新博主</h3>
	</caption>
	<thead class='thead-inverse'>
		<tr>
			<th>昵称</th>
			<th>性别</th>
			<th>加入时间</th>
		</tr>
	</thead>	
	<tbody>
	{% for wb_user in users %}
		<tr>
			<td><a href='{% url "wb:upage" %}?uid={{ wb_user.id }}'>{{ wb_user.name }}</td>
			<td>{{ wb_user.get_gender_display }}</td>
			<td>{{ wb_user.date_joined }}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
{% else %}
<h3 class='text-center'>注册</h3>
<form class="form-horizontal" method='POST' action='{% url "account:register" %}'>
	{% csrf_token %}
	<div class="form-group">
		<label class='col-md-1 text-right' for='input_username'>用户名：</label>
		<div class='col-md-10'>
			<input class='form-control' id='input_username' name='username' placeholder='用户名'>
		</div>
	</div>
	<div class="form-group">
		<label class='col-md-1 text-right' for='input_email'>邮箱：</label>
		<div class='col-md-10'>
			<input class='form-control' id='input_email' name='email' type='email' placeholder='邮箱'>
		</div>
	</div>
	<div class="form-group">
		<label class='col-md-1 text-right' for='input_password'>密码：</label>
		<div class='col-md-10'>
			<input class='form-control' id='input_password' name='password' type='password' placeholder='密码'>
		</div>
	</div>
	<div class="form-group">
		<label class='col-md-1 text-right' for='input_password2'>密码确认：</label>
		<div class='col-md-10'>
			<input class='form-control' id='input_password2' name='password2' type='password' placeholder='请再输一次'>
		</div>
	</div>
	<input class="btn btn-default" type='submit' value='提交'>
</form>
<hr />
<h3 class='text-center'>登录</h3>
<form class='form-horizontal' method='POST' action='{% url "account:login" %}'>
	{% csrf_token %}
	<div class="form-group">
		<label class='col-md-1 text-right' for='input_username'>用户名：</label>
		<div class='col-md-10'>
			<input class='form-control' id='input_username' name='username' placeholder='用户名'>
		</div>
	</div>
	<div class="form-group">
		<label class='col-md-1 text-right' for='input_password'>密码：</label>
		<div class='col-md-10'>
			<input class='form-control' id='input_password' name='password' type='password' placeholder='密码'>
		</div>
	</div>
	<input class="btn btn-default" type='submit' value='提交'>
</form>
{% endif %}
{% endblock %}
{% block base_content_to_footer %}<hr />{% endblock %}