crossin_weibo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from pro_weibo.views import index
from .views import Index

urlpatterns = [
    url(r'^weibo/', include('weibo.urls', namespace='wb')),
    url(r'^accounts/', include('account.urls', namespace='account')),
    url(r'^admin/', admin.site.urls),
    # url(r'^$', index, name='index'),
    url(r'^$', Index.as_view(), name='index'),
]

weibo/urls.py
from django.conf.urls import url
from weibo import views

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    # url(r'^$', views.HomePageView.as_view(), name='homepage'),
    url(r'^update', views.wb_update, name='update'),
    # url(r'^update', views.WBUpdate.as_view(), name='update'),
    # url(r'^u', views.UserPageView.as_view(), name='upage'),
    url(r'^comment', views.wb_comment, name='comment'),
    url(r'^forward', views.wb_forward, name='forward'),
    url(r'^follow', views.user_follow, name='follow'),
    url(r'^unfollow', views.user_unfollow, name='unfollow'),
    url(r'^u', views.user_page, name='upage'),
]

weibo/models.py
from django.db import models
from django.contrib.auth.models import User
import json
# Create your models here.


class WBUser(User):
    """
    继承 django 默认 User 类，扩充字段及方法
    """
    GENDER_OPTIONS = (
        (0, '保密'),
        (1, '男'),
        (2, '女'),
        (3, '其他')
    )
    nickname = models.CharField(verbose_name='昵称', max_length=60, null=True, blank=True)
    gender = models.IntegerField(verbose_name='性别', choices=GENDER_OPTIONS, default=0)
    _info = models.TextField(verbose_name='其他信息', blank=True, null=True)
    # ManyToManyField 的首个参数指定被关联的类，
    # 此处 WBUser 尚未定义完成，可用字符串形式“临时”代替，正式添加 followers 时，django 会自动替换为 WBUser 对象
    followers = models.ManyToManyField('WBUser', verbose_name='粉丝')

    @property
    def name(self):
        """
        返回用户名字，优先显示昵称
        装饰器 @property 可以使被装饰的函数以属性的形式调用，如 self.name
        """
        return self.nickname or self.username

    @property
    def info(self):
        """
        读取字段 _info，将 json 格式字符串转换为字典
        """
        return json.loads(self._info)

    def save_user_info(self, info: dict):
        """
        保存字段 _info，将字典转换为 json 格式的字符串
        info: dict —— `: dict` 用来指定参数 info 是类 dict 的对象，用来指定参数的格式
        """
        self._info = json.dumps(info)
        self.save()

    def follow(self, user: 'WBUser'):
        """
        关注
        user: 'WBUser' —— `: 'WBUser'` 用来指定参数 user 是类 WBUser 的对象，用来指定参数的格式
        此处 WBUser 尚未定义完成，可用字符串形式“临时”代替，正式添加传递参数时，django 会自动替换为 WBUser 对象
        """
        self.followers.add(user)

    def unfollow(self, user: 'WBUser'):
        """
        解除关注
        """
        self.followers.remove(user)

    def update(self, msg: str):
        """
        发布微博
        """
        wbt = WBText.objects.create(author=self, msg=msg)
        wb = WeiBo.objects.create(user=self, text=wbt)
        return wb

    def forward(self, wb: 'WeiBo'):
        """
        转发微博
        """
        return WeiBo.objects.create(user=self, text=wb.text)

    def __str__(self):
        return self.name


class WBText(models.Model):
    """
    文字微博
    """
    author = models.ForeignKey(WBUser, verbose_name='作者', related_name='ori_wbs')
    msg = models.TextField(verbose_name='微博', max_length=500)

    def __str__(self):
        return '{msg}...'.format(msg=self.msg[:20])


class WeiBo(models.Model):
    """
    微博信息
    """
    user = models.ForeignKey(WBUser, verbose_name='用户', related_name='wbs')
    time_create = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    is_del = models.BooleanField(verbose_name='是否删除', default=False)
    text = models.ForeignKey(WBText, verbose_name='文本', related_name='wbs')

    def del_this(self):
        """
        删除微博
        """
        self.is_del = True
        self.save()

    def comment_this(self, user: WBUser, text: str):
        """
        评论微博
        """
        comment = Comment.objects.create(target=self, user=user, text=text)
        return comment

    def __str__(self):
        return self.text.__str__()


class Comment(models.Model):
    """
    评论
    """
    target = models.ForeignKey(WeiBo, verbose_name='微博', related_name='comments')
    user = models.ForeignKey(WBUser, verbose_name='用户', related_name='comments')
    text = models.TextField(verbose_name='评论', max_length=500)
    time_create = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    is_del = models.BooleanField(verbose_name='是否删除', default=False)

    def del_this(self):
        """
        删除评论
        """
        self.is_del = True
        self.save()

    def __str__(self):
        return '{msg}...'.format(msg=self.text[:20])

weibo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
# from django.views import View
from django.contrib.auth.decorators import login_required
# from django.utils.decorators import method_decorator
from weibo.models import *
# Create your views here.


# @method_decorator(login_required, 'dispatch')
# class HomePageView(View):
#    """
#   class base views
#   """
#     def get(self, request):
#         wb_user = get_object_or_404(WBUser, id=request.user.id)
#         # wbs = WeiBo.objects.all().order_by('-time_create')
#         return render(request, 'weibo/homepage.html', {
#             'wb_user': wb_user,
#             # 'wbs': wbs
#         })


@login_required
def homepage(request):
    """
    个人中心
    """
    user = get_object_or_404(WBUser, id=request.user.id)
    wbs = WeiBo.objects.filter(user__in=user.followers.all()).order_by('-time_create')[:10]
    return render(request, 'weibo/homepage.html', {
        'user': user,
        'wbs': wbs
    })


# class UserPageView(View):
#     def get(self, request):
#         uid = request.GET.get('uid')
#         wb_user = get_object_or_404(WBUser, id=uid)
#         wbs = WeiBo.objects.filter(user=wb_user).order_by('-time_create')
#         return render(request, 'weibo/user_page.html', {
#             'wb_user': wb_user,
#             'wbs': wbs
#         })


def user_page(request):
    """
    用户主页
    """
    uid = request.GET.get('uid')
    wb_user = get_object_or_404(WBUser, id=uid)
    user = get_object_or_404(WBUser, id=request.user.id)
    wbs = WeiBo.objects.filter(user=wb_user).order_by('-time_create')
    return render(request, 'weibo/user_page.html', {
        'wb_user': wb_user,
        'wbs': wbs,
        'user': user
    })


# class WBUpdate(View):
#     def post(self, request):
#         wb_user = get_object_or_404(WBUser, id=request.user.id)
#         msg = request.POST.get('msg')
#         wb = wb_user.update(msg)
#         return HttpResponse(render(request, 'weibo/new_wb.html', {'wb': wb}))


def wb_update(request):
    """
    发送微博
    """
    wb_user = get_object_or_404(WBUser, id=request.user.id)
    msg = request.POST.get('msg')
    wb = wb_user.update(msg)
    return HttpResponse(render(request, 'weibo/new_wb.html', {'wb': wb}))


def wb_comment(request):
    """
    微博评论
    """
    wb_user = get_object_or_404(WBUser, id=request.user.id)
    msg = request.POST.get('msg')
    wid = request.POST.get('wid')
    wb = get_object_or_404(WeiBo, id=wid)
    comment = wb.comment_this(user=wb_user, text=msg)
    return HttpResponse(render(request, 'weibo/new_comm.html', {'comm': comment}))


def wb_forward(request):
    """
    微博转发
    """
    wb_user = get_object_or_404(WBUser, id=request.user.id)
    msg = request.POST.get('msg')
    wid = request.POST.get('wid')
    wb = get_object_or_404(WeiBo, id=wid)
    new_wb = wb_user.forward(wb)
    if msg:
        new_wb.comment_this(user=wb_user, text=msg)
    # redirect 接受 url name 参数，返回一个可以被 views return 返回的对象 HttpResponseRedirect
    response = redirect('wb:upage')
    # HttpResponseRedirect['Location'] 为跳转地址，下面的代码为地址直接拼接 get 参数
    response['Location'] += '?uid={uid}'.format(uid=wb_user.id)
    # HttpResponseRedirect 对象可以直接 return 返回，页面跳转到 response['Location'] 所指定的地址
    return response


def user_follow(request):
    """
    关注用户
    """
    uid = request.GET.get('uid')
    wb_user = get_object_or_404(WBUser, id=uid)
    user = get_object_or_404(WBUser, id=request.user.id)
    user.follow(wb_user)
    return HttpResponse()


def user_unfollow(request):
    """
    解除关注
    """
    uid = request.GET.get('uid')
    wb_user = get_object_or_404(WBUser, id=uid)
    user = get_object_or_404(WBUser, id=request.user.id)
    user.unfollow(wb_user)
    return HttpResponse()

weibo/templates/weibo/forward_modal.html
<div class="modal fade" id='forward_modal' tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">微博转发：</h4>
			</div>
			<div class="modal-body">
				<form class="form" id='forward_form' action='{% url "wb:forward" %}' method='POST'>
					{% csrf_token %}
					<textarea name='msg' class='form-control' placeholder='转发评论，上限500字符' rows=8 maxlength='500'></textarea>
					<input id='forward_weibo' class='hidden' name='wid'>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" id='btn-modal-hide' data-dismiss="modal">取消</button>
				<button type="submit" class="btn btn-primary" form='forward_form' onclick='wb_update()'>转发</button>
			</div>										
		</div>
	</div>
</div>

weibo/templates/weibo/homepage.html
{% extends 'base_page.html' %}
{% block title %}个人中心{% endblock %}
{% block left_more %}
<hr />
<div class='list-group'>
	<a href='#' class='list-group-item text-center list-group-item-info' data-toggle="modal" data-target="#wb_update_modal">发微博</a>
	<a href='#' class='list-group-item text-center list-group-item-info'>发图片</a>
</div>
{% endblock %}
{% block right %}
<div class="jumbotron">
  <h1>{{ user.name }} <small>欢迎回来</small></h1>
  <p><small>个性签名...</small></p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">修改资料</a></p>
</div>
<div class="hidden wb_list">
	<h1>我的最新微博</h1>
	<hr />
	<div class="wb_list_body" id='wb_update_list'></div>
</div>
<div class='wb_list'>
	<h1>最新好友微博</h1>
	<hr />
	<div class="wb_list_body">
	{% for wb in wbs %}
		{% include "weibo\list_wb.html" %}
	{% endfor %}
	</div>
</div>
{% endblock %}
{% block modal %}
<div class="modal fade" id='wb_update_modal' tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">发布微博：</h4>
			</div>
			<div class="modal-body">
				<form class="form" id='wb_update_form' action='{% url "wb:update" %}' method='POST'>
					{% csrf_token %}
					<textarea name='msg' class='form-control' placeholder='上限500字符' rows=8 maxlength='500'></textarea>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" id='btn-modal-hide' data-dismiss="modal">取消</button>
				<button type="submit" class="btn btn-primary" form='wb_update_form' onclick='wb_update()'>发布</button>
			</div>										
		</div>
	</div>
</div>

{% include "weibo\forward_modal.html" %}
{% endblock %}
{% block script %}
<script>
function wb_update(){
	// 更新微博
	document.getElementById('wb_update_form').onsubmit = function(e){
		e.preventDefault();
		var f = e.target,
			formData = new FormData(f),
			xhr = new XMLHttpRequest();
		xhr.open("POST", f.action, true);
		xhr.onreadystatechange=function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				var dataReply = xhr.responseText,
					para = document.getElementById('wb_update_list'),
					pp_attr = para.parentElement.getAttribute('class'),
					newBox = document.createElement('div');
				para.insertBefore(newBox, para.firstChild);
				newBox.innerHTML = dataReply;
				para.parentElement.setAttribute('class', pp_attr.replace('hidden', ''));
			};
		};
		xhr.send(formData);
		$('#wb_update_modal').modal('hide');
	};
};

{% include "weibo\page_js.html" %}
</script>
{% endblock %}

weibo/templates/weibo/list_wb.html
<div class="panel panel-info container-fluid">
	<div class="panel-heading row">
		<span class='col-md-4'>
		{% if wb.text.author == wb.user %}
			<small class='text-primary'><i>【原创】</i></small>
		{% else %}
			<small class='text-warning'><i>【转发】</i></small>
		{% endif %}
			作者: {{ wb.text.author }}
		</span>
		<span class='col-md-5'>时间: {{ wb.time_create }}</span>
		<a class='btn btn-default col-md-1' onclick=''>点赞: <span class="badge">0</span></a>
		{% if wb.user.id == user.id %}
		<a class='btn btn-default col-md-1' disabled>转发: <span class="badge">0</span></a>
		{% else %}
		<a class='btn btn-default col-md-1' data-toggle="modal" data-target="#forward_modal" onclick='forward_this({{ wb.id }})'>转发: <span class="badge">0</span></a>
		{% endif %}
		<a class='btn btn-default col-md-1' onclick='comm_this(this, {{ wb.id }})'>评论: <span class="badge">0</span></a>
	</div>
	<div class="panel-body">
		<p>{{ wb.text.msg }}</p>
	</div>
	<div class="panel-footer row">
		<ul class="list-group">
		{% for comm in wb.comments.all %}
			<li class='list-group-item'>
				{% include "weibo\new_comm.html" %}
			</li>
		{% endfor %}
		</ul>
	</div>
</div>

weibo/templates/weibo/new_comm.html
<h4>
	<span>{{ comm.user }}：</span>
	<a class='btn btn-default pull-right'>赞：<span class="badge">0</span></a>
</h4>
<hr />
<p>
	<p>{{ comm.text }}</p>
</p>
<p class='text-right'><small>——{{ comm.time_create }}</small></p>

weibo/templates/weibo/new_wb.html
<div class="panel panel-info container-fluid">
	<div class="panel-heading row">
		<span class='col-sm-5'>我的新微博</span>
		<span class='col-sm-5'>时间: {{ wb.time_create }}</span>
		<span class='col-sm-2 text-right'>原创</span>
	</div>
	<div class="panel-body">
		{{ wb.text.msg }}
	</div>
</div>

weibo/templates/weibo/page_js.html
function forward_this(wid){
	// 转发，向表格填入 weibo.id
	document.getElementById('forward_weibo').setAttribute('value', wid);
}
function comm_cancel(e){
	// 取消评论
	var comm = e.parentElement.parentElement.parentElement;
	comm.parentElement.removeChild(comm);
};

function comm_this(e, wid){
	// 开启评论
	var ee = e.parentElement.nextElementSibling,
		dd = document.createElement('div');
	dd.setAttribute('class', 'panel panel-primary container-fluid');
	dd.innerHTML = `\
		<div class="panel-heading row">\
			<span class="col-sm-1">评论：</span>\
			<span class="col-sm-1 pull-right"><input class="btn btn-success" type="submit" form="comm_form" onclick="comm_post(this)" value='发送'></span>\
			<span class="col-sm-1 pull-right"><a class="btn btn-danger" onclick="comm_cancel(this)">取消</a></span>\
		</div>\
		<div class="panel-body">\
			<form id="comm_form" method="POST" action="{% url "wb:comment" %}">\
				{% csrf_token %}\
				<textarea name="msg" class="form-control" placeholder="上限500字符" rows=8 maxlength=500></textarea>\
				<input class="hidden" name="wid" value="` + wid + `">\
			</form>\
		</div>`
	ee.appendChild(dd);
};

function comm_post(ee){
	// 发送评论
	document.getElementById('comm_form').onsubmit = function(e){
		e.preventDefault();
		var f = e.target,
			formData = new FormData(f),
			xhr = new XMLHttpRequest();
		xhr.open("POST", f.action, true);
		xhr.onreadystatechange=function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				var dataReply = xhr.responseText,
					para = ee.parentElement.parentElement.parentElement,
					newBox = document.createElement('li');
				newBox.setAttribute('class', 'list-group-item');
				newBox.innerHTML = dataReply;
				para.parentElement.nextElementSibling.querySelector('ul').appendChild(newBox);
				para.parentElement.removeChild(para);
			};
		};
		xhr.send(formData);
	};
};

weibo/templates/weibo/user_page.html
{% extends 'base_page.html' %}
{% block title %}{{ wb_user.name }} 的主页{% endblock %}
{% block right %}
<div class="jumbotron">
	<h1>{{ wb_user.name }} <small>的主页</small></h1>
	<p>个性签名...</p>
	<p>
	{% if wb_user in user.followers.all %}
		<a class="btn btn-success btn-lg" role="button" onclick='unfollow_this(this)'>已关注</a>
	{% elif wb_user.id == user.id %}
		<a class="btn btn-primary btn-lg" role="button" disabled>关注</a>
	{% else %}
		<a class="btn btn-primary btn-lg" role="button" onclick='follow_this(this)'>关注</a>
	{% endif %}
	</p>
</div>
{% for wb in wbs %}
	{% include "weibo\list_wb.html" %}
{% endfor %}
{% endblock %}
{% block modal %}
	{% include "weibo\forward_modal.html" %}
{% endblock %}
{% block script %}
<script>
function follow_this(e){
	// 关注用户
	var xhr = new XMLHttpRequest();
	xhr.open('GET', '{% url "wb:follow" %}?uid={{ wb_user.id }}', true);
	xhr.onreadystatechange=function(){
		if(xhr.readyState == 4 && xhr.status == 200){
			e.setAttribute('onclick', 'unfollow_this(this)');
			e.setAttribute('class', 'btn btn-success btn-lg');
			e.innerText = '已关注';
		};
	};
	xhr.send();
};

function unfollow_this(e){
	// 解除关注
	var xhr = new XMLHttpRequest();
	xhr.open('GET', '{% url "wb:unfollow" %}?uid={{ wb_user.id }}', true);
	xhr.onreadystatechange=function(){
		if(xhr.readyState == 4 && xhr.status == 200){
			e.setAttribute('onclick', 'follow_this(this)');
			e.setAttribute('class', 'btn btn-primary btn-lg');
			e.innerText = '关注';
		};
	};
	xhr.send();	
}

{% include "weibo\page_js.html" %}
</script>
{% endblock %}